import 'package:escrowcorner/view/Home_Screens/screen_home.dart';
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'view/Home_Screens/screen_reset_password.dart';
import 'view/screens/login/screen_login.dart';
import 'view/screens/dashboard/screen_dashboard.dart';
import 'widgets/custom_token/constant_token.dart';
import 'package:escrowcorner/view/screens/user_profile/user_profile_controller.dart';
import 'package:escrowcorner/view/controller/dynamic_branding_controller.dart';
import 'package:escrowcorner/view/controller/language_controller.dart';
import 'package:escrowcorner/view/screens/settings/setting_controller.dart';

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  // Register UserProfileController globally
  Get.put(UserProfileController(), permanent: true);
  // Register DynamicBrandingController globally
  Get.put(DynamicBrandingController(), permanent: true);
  // Register LanguageController globally
  Get.put(LanguageController(), permanent: true);
  // Register SettingController globally
  Get.put(SettingController(), permanent: true);
  runApp(MyApp());
}



class MyApp extends StatelessWidget {
  const MyApp({super.key});
  @override
  Widget build(BuildContext context) {
    return GetMaterialApp(
      debugShowCheckedModeBanner: false,
      home: AuthWrapper(),
      // Enable internationalization - start with English by default
      locale: Locale('en'), // Always start with English
      fallbackLocale: Locale('en'),
      translations: AppTranslations(),
      getPages: [
        GetPage(name: '/reset-password', page: () => ScreenResetPassword()),
        GetPage(name: '/login', page: () => ScreenLogin()),
        GetPage(name: '/dashboard', page: () => ScreenDashboard()),
      ],
    );
  }
}

class AuthWrapper extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return FutureBuilder<bool>(
      future: isUserLoggedIn(),
      builder: (context, snapshot) {
        if (snapshot.connectionState == ConnectionState.waiting) {
          return Scaffold(
            backgroundColor: Color(0xffE6F0F7),
            body: Center(
              child: CircularProgressIndicator(
                valueColor: AlwaysStoppedAnimation<Color>(Colors.green),
              ),
            ),
          );
        }
        
        final isLoggedIn = snapshot.data ?? false;
        
        if (isLoggedIn) {
          // User is logged in, show dashboard
          return ScreenDashboard();
        } else {
          // User is not logged in, show home screen
          return ScreenHome();
        }
      },
    );
  }
}

// App translations class
class AppTranslations extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en': {
      'select_language': 'Select Language',
      'change_language': 'Change Language',
      'failed_to_load_languages': 'Failed to load languages',
      'retry': 'Retry',
      'loading': 'Loading...',
      'welcome': 'Welcome',
      'home': 'Home',
      'services': 'Services',
      'our_services': 'Our Services',
      'error_fetching_services': 'Error fetching services.',
      'no_services_available': 'No services available.',
      'about': 'About',
      'contact': 'Contact',
      'login': 'Login',
      'register': 'Register',
      'logout': 'Logout',
      'profile': 'Profile',
      'settings': 'Settings',
      'dashboard': 'Dashboard',
      'language': 'Language',
      'language_demo': 'Language Demo',
      'current_language': 'Current Language',
      'sample_content': 'Sample Content',
      'language_info': 'Language Information',
      'available_languages': 'Available Languages',
      'country': 'Country',
      'phone': 'Phone',
      'email': 'Email',
      'password': 'Password',
      'confirm_password': 'Confirm Password',
      'new_password': 'New Password',
      'first_name': 'First Name',
      'last_name': 'Last Name',
      'username': 'Username',
      'submit': 'Submit',
      'cancel': 'Cancel',
      'save': 'Save',
      'edit': 'Edit',
      'delete': 'Delete',
      'search': 'Search',
      'filter': 'Filter',
      'sort': 'Sort',
      'refresh': 'Refresh',
      'back': 'Back',
      'next': 'Next',
      'previous': 'Previous',
      'done': 'Done',
      'close': 'Close',
      'ok': 'OK',
      'yes': 'Yes',
      'no': 'No',
      'error': 'Error',
      'success': 'Success',
      'warning': 'Warning',
      'info': 'Information',
      'please_wait': 'Please wait...',
      'no_data_found': 'No data found',
      'try_again': 'Try again',
      'network_error': 'Network error',
      'server_error': 'Server error',
      'invalid_input': 'Invalid input',
      'required_field': 'This field is required',
      'invalid_email': 'Invalid email address',
      'password_mismatch': 'Passwords do not match',
      'password_too_short': 'Password is too short',
      'please_fill_in_all_fields': 'Please fill in all fields',
      'user_registered': 'User registered successfully',
      'verification_required': 'Verification required',
      'otp_sent': 'OTP sent to your email',
      'enter_otp': 'Enter the OTP sent to your email',
      'enter_the_code_sent_to_your_email': 'Enter the code sent to your email',
      'enter_code': 'Enter Code',
      'please_enter_the_otp_code': 'Please enter the OTP code',
      'email_verified': 'Email verified',
      'otp_resent_successfully': 'OTP resent successfully',
      'failed_to_resend_otp': 'Failed to resend OTP',
      'verify': 'Verify',
      'resend_otp': 'Resend OTP',
      'otp_expired': 'OTP has expired',
      'invalid_otp': 'Invalid OTP',
      'verification_successful': 'Verification successful',
      'verification_failed': 'Verification failed',
      'login_successful': 'Login successful',
      'login_failed': 'Login failed',
      'logout_successful': 'Logout successful',
      'session_expired': 'Session expired',
      'unauthorized': 'Unauthorized access',
      'forbidden': 'Access forbidden',
      'not_found': 'Resource not found',
      'internal_error': 'Internal server error',
      'bad_request': 'Bad request',
      'timeout': 'Request timeout',
      'connection_error': 'Connection error',
      'file_upload_failed': 'File upload failed',
      'file_too_large': 'File is too large',
      'unsupported_file_type': 'Unsupported file type',
      'camera_permission_denied': 'Camera permission denied',
      'gallery_permission_denied': 'Gallery permission denied',
      'location_permission_denied': 'Location permission denied',
      'notification_permission_denied': 'Notification permission denied',
      'permission_required': 'Permission required',
      'go_to_settings': 'Go to settings',
      'allow': 'Allow',
      'deny': 'Deny',
      'later': 'Later',
      'never': 'Never',
      'always': 'Always',
      'today': 'Today',
      'yesterday': 'Yesterday',
      'tomorrow': 'Tomorrow',
      'this_week': 'This week',
      'last_week': 'Last week',
      'next_week': 'Next week',
      'this_month': 'This month',
      'last_month': 'Last month',
      'next_month': 'Next month',
      'this_year': 'This year',
      'last_year': 'Last year',
      'next_year': 'Next year',
      'january': 'January',
      'february': 'February',
      'march': 'March',
      'april': 'April',
      'may': 'May',
      'june': 'June',
      'july': 'July',
      'august': 'August',
      'september': 'September',
      'october': 'October',
      'november': 'November',
      'december': 'December',
      'monday': 'Monday',
      'tuesday': 'Tuesday',
      'wednesday': 'Wednesday',
      'thursday': 'Thursday',
      'friday': 'Friday',
      'saturday': 'Saturday',
      'sunday': 'Sunday',
      'morning': 'Morning',
      'afternoon': 'Afternoon',
      'evening': 'Evening',
      'night': 'Night',
      'am': 'AM',
      'pm': 'PM',
      'second': 'Second',
      'minute': 'Minute',
      'hour': 'Hour',
      'day': 'Day',
      'week': 'Week',
      'month': 'Month',
      'year': 'Year',
      'seconds': 'Seconds',
      'minutes': 'Minutes',
      'hours': 'Hours',
      'days': 'Days',
      'weeks': 'Weeks',
      'months': 'Months',
      'years': 'Years',
      'ago': 'ago',
      'from_now': 'from now',
      'just_now': 'just now',
      'a_moment_ago': 'a moment ago',
      'in_a_moment': 'in a moment',
      'in_a_few_seconds': 'in a few seconds',
      'in_a_few_minutes': 'in a few minutes',
      'in_a_few_hours': 'in a few hours',
      'in_a_few_days': 'in a few days',
             // Deposit screen translations
       'my_deposits': 'My Deposits',
       'my_withdrawals': 'My Withdrawals',
       'serial_no': 'Sr No.',
      'date_time': 'Date Time',
      'transaction_id': 'Transaction ID',
      'method': 'Method',
      'currency': 'Currency',
      'gross': 'Gross',
      'fee': 'Fee',
      'net': 'Net',
      'status': 'Status',
             'your_account_is_fresh_and_new': 'Your account is Fresh and New!',
       'start_by_requesting_money_from_friends_or_by_selling_online_and_collecting_payments_in_your_wallet': 'Start by requesting money from friends or by selling online and collecting payments in your wallet.',
       // Status translations
       'completed': 'Completed',
       'pending': 'Pending',
       'failed': 'Failed',
       'cancelled': 'Cancelled',
       'processing': 'Processing',
       'approved': 'Approved',
       'rejected': 'Rejected',
       'in_a_few_weeks': 'in a few weeks',
      'in_a_few_months': 'in a few months',
      'in_a_few_years': 'in a few years',
      
      // Escrow related translations
      'escrow_detail': 'Escrow Detail',
      'loading_escrow_details': 'Loading escrow details...',
      'no_details_available': 'No Details Available',
      'holding_period': 'Holding Period:',
      'created_at': 'Created at:',
      'sender_email': 'Sender Email:',
      'receiver_email': 'Receiver Email:',
      'status': 'Status:',
      'method': 'Method:',
      'gross': 'Gross:',
      'fee': 'Fee:',
      'net': 'Net:',
      'days': 'days',
              'release_payment': 'Release Payment',
        'release': 'Release',
        'reject_payment': 'Reject Payment',
      'message': 'Message',
      'file_download': 'File Download',
      'file_not_download': 'File Not Download',
      'error_downloading_file': 'Error downloading file',
      
      // Escrow list translations
      'send_escrow': 'Send Escrow',
      'add_escrow': 'Add Escrow',
      'escrow': 'Escrow',
      'no_escrows_available': 'No escrows available',
      'date': 'Date:',
      'amount': 'Amount:',
      'from': 'From:',
      'to': 'To:',
      'view': 'View',
      'information': 'Information',
      'failed_to_open_detail_screen': 'Failed to open detail screen',
      
      // Escrow information translations
      'escrow_information': 'Escrow Information',
      'loading_escrow_information': 'Loading escrow information...',
      'no_information_available': 'No Information Available',
      'category': 'Category:',
              'description': 'Description:',
                 'note_for_the_seller': 'Note for the Seller',
        'your_agreement': 'Your Agreement',
        'product_name': 'Product Name:',
        'agreement': 'Agreement:',
              'product_photos_or_information': 'Product Photos or Information:',
        'click_download_to_save': 'Click Download to save file',
        'download': 'Download',
        'download_attachment': 'Download Attachment',
        'downloading_file': 'Downloading {fileName}...',
      'download_successful': 'Download Successful',
      'file_downloaded_to_device': '{fileName} has been downloaded to your device',
      'download_failed': 'Download Failed',
      'failed_to_download_file': 'Failed to download {fileName}. Status: {status}',
      'download_error': 'Download Error',
      'error_downloading_file': 'Error downloading {fileName}: {error}',
      'escrow_released_successfully': 'Escrow released successfully',
      'failed_to_release_escrow': 'Failed to release escrow',
      
      // Form field translations
      'title': 'Title',
      'enter_title': 'Enter title',
      'recipient_email': 'Recipient Email',
      'enter_recipient_email': 'Ex: example@example.com',
      'category_of_the_escrow': 'Category of the escrow',
      'currency': 'Currency',
      'payment_method': 'Payment Method',
      'loading_payment_methods': 'Loading payment methods...',
      'no_payment_methods_available': 'No payment methods available',
      'escrow_fee': 'Escrow Fee',
      'fixed_fee': 'Fixed Fee',
      'percentage_fee': 'Percentage Fee',
      'total_amount': 'Total Amount',
      'fee': 'Fee',
      'note_for_the_recipient': 'Note for Recipient',
      'write_a_note': 'Write a note...',
      'choose_files': 'Choose Files',
      'add_more_files': 'Add More Files',
      'select_image': 'Select Image',
      'select_file': 'Select File',
      'selected_files_count': 'Selected Files ({count}):',
      'enter_product_name': 'Enter product name',
      'no_description_provided': 'No description provided',
      'accept': 'Accept',
      'terms_and_conditions': 'Terms & Conditions',
      'start_escrow': 'Start Escrow',
      'request_escrow': 'Request Escrow',
      'what_is_escrow_and_how_does_it_work': 'What is Escrow and How does it work ?',
      'refresh_fees': 'Refresh fees',
      'loading_escrow_fees': 'Loading escrow fees...',
      'title_is_required': 'Title is required.',
      'please_enter_a_valid_email_address': 'Please enter a valid email address.',
      'please_select_a_valid_category': 'Please select a valid category.',
      'please_select_a_valid_currency': 'Please select a valid currency.',
      'please_enter_a_valid_amount_greater_than_zero': 'Please enter a valid amount greater than zero.',
      'note_for_recipient_is_required': 'Note for recipient is required.',
      'you_must_accept_the_terms_and_conditions': 'You must accept the terms and conditions.',
             'maximum_five_files_are_allowed': 'Maximum five files are allowed',
       'error_loading_home_content': 'Error loading home content',
       'check_internet_connection': 'Please check your internet connection',
       'get_started': 'Get Started',
       'token_not_found': 'Authentication token not found',
       'escrow_stored_successfully': 'Escrow stored successfully',
       'an_error_occurred': 'An error occurred',
       'an_unexpected_error_occurred_please_try_again': 'An unexpected error occurred. Please try again.',
       'please_upload_product_photo_or_information': 'Please upload a product photo or information',
       'cancelled_escrow_information': 'Cancelled Escrow Information',
       'could_not_launch_url': 'Could not launch URL',
       'attachment': 'Attachment',
       'otp_resent_successfully': 'OTP resent successfully',
       'failed_to_resend_otp': 'Failed to resend OTP',
       'kyc_required': 'KYC Required',
       'in_order_to_deposit_submit_kyc_first': 'In order to deposit, submit KYC first',
       'visit_website_to_complete_kyc': 'Visit website to complete KYC',
       'escrow_created_successfully': 'Escrow created successfully',
       'cancelled_escrow_details': 'Cancelled Escrow Details',
       'no_information_available': 'No Information Available',
       'no_details_available': 'No Details Available',
       'loading_escrow_details': 'Loading escrow details...',
       'loading_escrow_information': 'Loading escrow information...',
       'escrow_released_successfully': 'Escrow released successfully',
       'please_select_a_valid_method': 'Please select a valid method',
       'enter_a_valid_amount': 'Enter a valid amount',
       'enter_phone_number': 'Enter phone number',
       'funding_damaspay_account': 'Funding Damaspay Account',
       'payment_method': 'Payment Method',
       'amount': 'Amount',
       'phone_number': 'Phone Number',
       'submit': 'Submit',
               'no_payment_methods_available': 'No payment methods available. Please try again later.',
        'select_image': 'Select Image',
        'select_file': 'Select File',
        'deposit': 'Deposit',
        'withdraw': 'Withdraw',
        'in_order_to_withdraw_submit_kyc_first': 'In order to withdraw, submit KYC first',
        'visit_website_to_complete_kyc': 'Visit website to complete KYC',
        'ok': 'OK',
        // Transaction screen translations
        'all_transactions': 'All Transactions',
        'filters': 'Filters',
        'all_types': 'All Types',
        'withdrawals': 'Withdrawals',
        'deposits': 'Deposits',
            'payment_method': 'Payment Method',
    'operators': 'Operators',
          'select_method': 'Select Method',
      'select_date': 'Select Date',
        'all_status': 'All Status',
        'time_order': 'Time Order',
        'time_ascending': 'Time Ascending',
        'time_descending': 'Time Descending',
        'from_date': 'From Date',
        'to_date': 'To Date',
        'phone_number': 'Phone Number',
                 'view': 'View',
         'no_data_available': 'No Data Available',
                  'activity_title': 'Activity Title',
         'balance': 'Balance',
         'merchant': 'Merchant',
         'add_sub_account': 'ADD SUB ACCOUNT',
         'no_sub_accounts_found': 'No sub accounts found',
         'sub_account_name': 'Sub Account Name:',
      'please_enter_sub_account_name': 'Please enter sub account name',
         'mtn_orange_balance': 'MTN & Orange Balance:',
         'detail': 'Detail',
         'transfer_in': 'Transfer In',
         'transfer_out': 'Transfer Out',
                   'please_contact_support_to_update_the_sub_account': 'Please contact support to update the sub account',
          'transaction_history': 'Transaction History',
          'filter': 'Filter',
          'today': 'Today',
          'weekly': 'This Week',
          'monthly': 'This Month',
          'yearly': 'This Year',
          'no_transactions_found': 'No Transactions Found',
          'no_transactions_for_sub_account': 'There are no transactions for this sub account yet.',
          'transaction_id': 'Transaction ID',
          'date_time': 'Date & Time',
          'method': 'Method',
          'description': 'Description',
          'gross_amount': 'Gross Amount',
          'fee': 'Fee',
          'net_amount': 'Net Amount',
          'balance': 'Balance',
          'enter_amount': 'Enter amount',
          'please_enter_amount': 'Please enter an amount',
          'please_select_payment_method': 'Please select a payment method',
          'please_enter_valid_amount': 'Please enter a valid amount',
          'add_merchant': 'Add Merchant',
          'new_sub_account': 'New Sub Account',
          'sub_account_logo': 'Sub Account Logo',
      'sub_account_logo_required': 'Sub Account Logo is required',
             'sub_account_logo_is_requird': 'Sub Account Logo is required',
           'sub_account_description': 'Sub Account Description',
                  'sub_account_description_required': 'Sub account description is required',
                  'merchant_created_successfully': 'Merchant created successfully',
       'sub_added_successfully': 'Sub account added successfully',
       'choose_file': 'Choose a File',
          'no_file_chosen': 'No file chosen',
          'write_description': 'Write description...',
    },
    'fr': {
      'select_language': 'Sélectionner la langue',
      'change_language': 'Changer de langue',
      'failed_to_load_languages': 'Échec du chargement des langues',
      'retry': 'Réessayer',
      'loading': 'Chargement...',
      'welcome': 'Bienvenue',
      'home': 'Accueil',
      'services': 'Services',
      'our_services': 'Nos Services',
      'error_fetching_services': 'Erreur lors de la récupération des services.',
      'no_services_available': 'Aucun service disponible.',
      'about': 'À propos',
      'contact': 'Contact',
      'login': 'Connexion',
      'register': 'S\'inscrire',
      'logout': 'Déconnexion',
      'profile': 'Profil',
      'settings': 'Paramètres',
      'dashboard': 'Tableau de bord',
      'language': 'Langue',
      'language_demo': 'Démo de Langue',
      'current_language': 'Langue Actuelle',
      'sample_content': 'Contenu d\'Exemple',
      'language_info': 'Informations sur la Langue',
      'available_languages': 'Langues Disponibles',
      'country': 'Pays',
      'phone': 'Téléphone',
      'email': 'E-mail',
      'password': 'Mot de passe',
      'confirm_password': 'Confirmer le mot de passe',
      'new_password': 'Nouveau mot de passe',
      'first_name': 'Prénom',
      'last_name': 'Nom de famille',
      'username': 'Nom d\'utilisateur',
      'submit': 'Soumettre',
      'cancel': 'Annuler',
      'save': 'Enregistrer',
      'edit': 'Modifier',
      'delete': 'Supprimer',
      'search': 'Rechercher',
      'filter': 'Filtrer',
      'sort': 'Trier',
      'refresh': 'Actualiser',
      'back': 'Retour',
      'next': 'Suivant',
      'previous': 'Précédent',
      'done': 'Terminé',
      'close': 'Fermer',
      'ok': 'OK',
      'yes': 'Oui',
      'no': 'Non',
      'error': 'Erreur',
      'success': 'Succès',
      'warning': 'Avertissement',
      'info': 'Information',
      'please_wait': 'Veuillez patienter...',
      'no_data_found': 'Aucune donnée trouvée',
      'try_again': 'Réessayer',
      'network_error': 'Erreur réseau',
      'server_error': 'Erreur serveur',
      'invalid_input': 'Entrée invalide',
      'required_field': 'Ce champ est requis',
      'invalid_email': 'Adresse e-mail invalide',
      'password_mismatch': 'Les mots de passe ne correspondent pas',
      'password_too_short': 'Le mot de passe est trop court',
      'please_fill_in_all_fields': 'Veuillez remplir tous les champs',
      'user_registered': 'Utilisateur inscrit avec succès',
      'verification_required': 'Vérification requise',
      'otp_sent': 'OTP envoyé à votre e-mail',
      'enter_otp': 'Entrez l\'OTP envoyé à votre e-mail',
      'enter_the_code_sent_to_your_email': 'Entrez le code envoyé à votre e-mail',
      'enter_code': 'Entrez le code',
      'please_enter_the_otp_code': 'Veuillez entrer le code OTP',
      'email_verified': 'E-mail vérifié',
      'otp_resent_successfully': 'OTP renvoyé avec succès',
             'failed_to_resend_otp': 'Échec du renvoi de l\'OTP',
       'kyc_required': 'KYC Requis',
       'in_order_to_deposit_submit_kyc_first': 'Pour effectuer un dépôt, soumettez d\'abord votre KYC',
       'visit_website_to_complete_kyc': 'Visitez le site web pour compléter votre KYC',
       'escrow_created_successfully': 'Escrow créé avec succès',
       'cancelled_escrow_details': 'Détails de l\'Escrow Annulé',
       'no_information_available': 'Aucune Information Disponible',
       'no_details_available': 'Aucun Détail Disponible',
       'loading_escrow_details': 'Chargement des détails de l\'escrow...',
       'add_merchant': 'Ajouter un Marchand',
       'new_sub_account': 'Nouveau Compte Sous',
       'sub_account_logo': 'Logo du Compte Sous',
      'sub_account_logo_required': 'Le Logo du Compte Sous est requis',
             'sub_account_logo_is_requird': 'Le Logo du Compte Sous est requis',
        'sub_account_description': 'Description du Compte Sous',
                 'sub_account_description_required': 'La description du compte sous est requise',
                 'merchant_created_successfully': 'Marchand créé avec succès',
         'sub_added_successfully': 'Compte sous ajouté avec succès',
         'choose_file': 'Choisir un Fichier',
       'no_file_chosen': 'Aucun fichier choisi',
       'write_description': 'Écrire une description...',
       'loading_escrow_information': 'Chargement des informations sur l\'escrow...',
       'escrow_released_successfully': 'Escrow libéré avec succès',
       'please_select_a_valid_method': 'Veuillez sélectionner une méthode valide',
       'enter_a_valid_amount': 'Entrez un montant valide',
       'enter_phone_number': 'Entrez le numéro de téléphone',
       'funding_damaspay_account': 'Financement du Compte Damaspay',
       'payment_method': 'Méthode de Paiement',
       'amount': 'Montant',
       'enter_amount': 'Entrez le montant',
       'please_enter_amount': 'Veuillez entrer un montant',
       'please_select_payment_method': 'Veuillez sélectionner une méthode de paiement',
       'please_enter_valid_amount': 'Veuillez entrer un montant valide',
       'phone_number': 'Numéro de Téléphone',
       'submit': 'Soumettre',
               'no_payment_methods_available': 'Aucune méthode de paiement disponible. Veuillez réessayer plus tard.',
        'select_image': 'Sélectionner l\'Image',
        'select_file': 'Sélectionner le Fichier',
        'deposit': 'Dépôt',
        'withdraw': 'Retrait',
        'in_order_to_withdraw_submit_kyc_first': 'Pour effectuer un retrait, soumettez d\'abord votre KYC',
        'visit_website_to_complete_kyc': 'Visitez le site web pour compléter votre KYC',
        'ok': 'OK',
      'select_language': 'Sélectionner la langue',
      'verify': 'Vérifier',
      'resend_otp': 'Renvoyer l\'OTP',
      'otp_expired': 'L\'OTP a expiré',
      'invalid_otp': 'OTP invalide',
      'verification_successful': 'Vérification réussie',
      'verification_failed': 'Échec de la vérification',
      'login_successful': 'Connexion réussie',
      'login_failed': 'Échec de la connexion',
      'logout_successful': 'Déconnexion réussie',
      'session_expired': 'Session expirée',
      'unauthorized': 'Accès non autorisé',
      'forbidden': 'Accès interdit',
      'not_found': 'Ressource non trouvée',
      'internal_error': 'Erreur interne du serveur',
      'bad_request': 'Mauvaise requête',
      'timeout': 'Délai d\'attente de la requête',
      'connection_error': 'Erreur de connexion',
      'file_upload_failed': 'Échec du téléchargement du fichier',
      'file_too_large': 'Le fichier est trop volumineux',
      'unsupported_file_type': 'Type de fichier non pris en charge',
      'camera_permission_denied': 'Permission d\'accès à la caméra refusée',
      'gallery_permission_denied': 'Permission d\'accès à la galerie refusée',
      'location_permission_denied': 'Permission d\'accès à l\'emplacement refusée',
      'notification_permission_denied': 'Permission de notification refusée',
      'permission_required': 'Permission requise',
      'go_to_settings': 'Aller aux paramètres',
      'allow': 'Autoriser',
      'deny': 'Refuser',
      'later': 'Plus tard',
      'never': 'Jamais',
      'always': 'Toujours',
      'today': 'Aujourd\'hui',
      'yesterday': 'Hier',
      'tomorrow': 'Demain',
      'this_week': 'Cette semaine',
      'last_week': 'La semaine dernière',
      'next_week': 'La semaine prochaine',
      'this_month': 'Ce mois',
      'last_month': 'Le mois dernier',
      'next_month': 'Le mois prochain',
      'this_year': 'Cette année',
      'last_year': 'L\'année dernière',
      'next_year': 'L\'année prochaine',
      'january': 'Janvier',
      'february': 'Février',
      'march': 'Mars',
      'april': 'Avril',
      'may': 'Mai',
      'june': 'Juin',
      'july': 'Juillet',
      'august': 'Août',
      'saturday': 'Samedi',
      'sunday': 'Dimanche',
      'morning': 'Matin',
      'afternoon': 'Après-midi',
      'evening': 'Soirée',
      'night': 'Nuit',
      'am': 'AM',
      'pm': 'PM',
      'second': 'Seconde',
      'minute': 'Minute',
      'hour': 'Heure',
      'day': 'Jour',
      'week': 'Semaine',
      'month': 'Mois',
      'year': 'Année',
      'seconds': 'Secondes',
      'minutes': 'Minutes',
      'hours': 'Heures',
      'days': 'Jours',
      'weeks': 'Semaines',
      'months': 'Mois',
      'years': 'Années',
      'ago': 'il y a',
      'from_now': 'à partir de maintenant',
      'just_now': 'à l\'instant',
      'a_moment_ago': 'il y a un moment',
      'in_a_moment': 'dans un moment',
      'in_a_few_seconds': 'dans quelques secondes',
      'in_a_few_minutes': 'dans quelques minutes',
      'in_a_few_hours': 'dans quelques heures',
      'in_a_few_days': 'dans quelques jours',
      'in_a_few_weeks': 'dans quelques semaines',
      'in_a_few_months': 'dans quelques mois',
      'in_a_few_years': 'dans quelques années',
      
             // Deposit screen translations
       'my_deposits': 'Mes Dépôts',
       'my_withdrawals': 'Mes Retraits',
       'serial_no': 'N° Série',
      'date_time': 'Date Heure',
      'transaction_id': 'ID Transaction',
      'method': 'Méthode',
      'currency': 'Devise',
      'gross': 'Brut',
      'fee': 'Frais',
      'net': 'Net',
      'status': 'Statut',
             'your_account_is_fresh_and_new': 'Votre compte est Frais et Nouveau !',
       'start_by_requesting_money_from_friends_or_by_selling_online_and_collecting_payments_in_your_wallet': 'Commencez par demander de l\'argent à des amis ou en vendant en ligne et en collectant des paiements dans votre portefeuille.',
       // Status translations
       'completed': 'Terminé',
       'pending': 'En attente',
       'failed': 'Échoué',
       'cancelled': 'Annulé',
       'processing': 'En cours',
       'approved': 'Approuvé',
       'rejected': 'Rejeté',
       
       // Escrow related translations
      'escrow_detail': 'Détails de l\'Escrow',
      'loading_escrow_details': 'Chargement des détails de l\'escrow...',
      'no_details_available': 'Aucun détail disponible',
      'holding_period': 'Période de détention:',
      'created_at': 'Créé le:',
      'sender_email': 'Email de l\'expéditeur:',
      'receiver_email': 'Email du destinataire:',
      'status': 'Statut:',
      'method': 'Méthode:',
      'gross': 'Brut:',
      'fee': 'Frais:',
      'net': 'Net:',
      'days': 'jours',
              'release_payment': 'Libérer le paiement',
        'release': 'Libérer',
        'reject_payment': 'Rejeter le paiement',
      'message': 'Message',
      'file_download': 'Téléchargement de fichier',
      'file_not_download': 'Fichier non téléchargé',
      'error_downloading_file': 'Erreur lors du téléchargement du fichier',
      
      // Escrow list translations
      'send_escrow': 'Envoyer l\'Escrow',
      'add_escrow': 'Ajouter l\'Escrow',
      'escrow': 'Escrow',
      'no_escrows_available': 'Aucun escrow disponible',
      'date': 'Date:',
      'amount': 'Montant:',
      'from': 'De:',
      'to': 'À:',
      'view': 'Voir',
      'information': 'Information',
      'failed_to_open_detail_screen': 'Échec de l\'ouverture de l\'écran de détail',
      
      // Escrow information translations
      'escrow_information': 'Informations sur l\'Escrow',
      'loading_escrow_information': 'Chargement des informations sur l\'escrow...',
      'no_information_available': 'Aucune information disponible',
      'category': 'Catégorie:',
              'description': 'Description:',
                 'note_for_the_seller': 'Note pour le Vendeur',
        'your_agreement': 'Votre Accord',
        'product_name': 'Nom du produit:',
        'agreement': 'Accord:',
              'product_photos_or_information': 'Photos ou Informations du Produit:',
        'click_download_to_save': 'Cliquez sur Télécharger pour enregistrer le fichier',
        'download': 'Télécharger',
        'download_attachment': 'Télécharger la Pièce Jointe',
        'downloading_file': 'Téléchargement de {fileName}...',
      'download_successful': 'Téléchargement réussi',
      'file_downloaded_to_device': '{fileName} a été téléchargé sur votre appareil',
      'download_failed': 'Échec du téléchargement',
      'failed_to_download_file': 'Échec du téléchargement de {fileName}. Statut: {status}',
      'download_error': 'Erreur de téléchargement',
      'error_downloading_file': 'Erreur de téléchargement de {fileName}: {error}',
      'escrow_released_successfully': 'Escrow libéré avec succès',
      'failed_to_release_escrow': 'Échec de la libération de l\'escrow',
      
      // Form field translations
      'title': 'Titre',
      'enter_title': 'Entrer le titre',
      'recipient_email': 'Email du Destinataire',
      'enter_recipient_email': 'Ex: exemple@exemple.com',
      'category_of_the_escrow': 'Catégorie de l\'escrow',
      'currency': 'Devise',
      'payment_method': 'Méthode de Paiement',
      'loading_payment_methods': 'Chargement des méthodes de paiement...',
      'no_payment_methods_available': 'Aucune méthode de paiement disponible',
      'escrow_fee': 'Frais d\'Escrow',
      'fixed_fee': 'Frais Fixe',
      'percentage_fee': 'Frais en Pourcentage',
      'total_amount': 'Montant Total',
      'fee': 'Frais',
      'note_for_the_recipient': 'Note pour le Destinataire',
      'write_a_note': 'Écrire une note...',
      'choose_files': 'Choisir des Fichiers',
      'add_more_files': 'Ajouter Plus de Fichiers',
      'select_image': 'Sélectionner l\'Image',
      'select_file': 'Sélectionner le Fichier',
      'selected_files_count': 'Fichiers Sélectionnés ({count}):',
      'enter_product_name': 'Entrer le nom du produit',
      'no_description_provided': 'Aucune description fournie',
      'accept': 'Accepter',
      'terms_and_conditions': 'Termes et Conditions',
      'start_escrow': 'Démarrer l\'Escrow',
      'request_escrow': 'Demander l\'Escrow',
      'what_is_escrow_and_how_does_it_work': 'Qu\'est-ce que l\'Escrow et comment ça marche ?',
      'refresh_fees': 'Actualiser les frais',
      'loading_escrow_fees': 'Chargement des frais d\'escrow...',
      'title_is_required': 'Le titre est requis.',
      'please_enter_a_valid_email_address': 'Veuillez entrer une adresse email valide.',
      'please_select_a_valid_category': 'Veuillez sélectionner une catégorie valide.',
      'please_select_a_valid_currency': 'Veuillez sélectionner une devise valide.',
      'please_enter_a_valid_amount_greater_than_zero': 'Veuillez entrer un montant valide supérieur à zéro.',
      'note_for_recipient_is_required': 'La note pour le destinataire est requise.',
      'you_must_accept_the_terms_and_conditions': 'Vous devez accepter les termes et conditions.',
             'maximum_five_files_are_allowed': 'Maximum cinq fichiers sont autorisés',
       'error_loading_home_content': 'Erreur lors du chargement du contenu de la page d\'accueil',
       'check_internet_connection': 'Veuillez vérifier votre connexion internet',
       'get_started': 'Commencer',
       'token_not_found': 'Jeton d\'authentification introuvable',
       'escrow_stored_successfully': 'Escrow stocké avec succès',
       'an_error_occurred': 'Une erreur s\'est produite',
       'an_unexpected_error_occurred_please_try_again': 'Une erreur inattendue s\'est produite. Veuillez réessayer.',
       'please_upload_product_photo_or_information': 'Veuillez télécharger une photo du produit ou des informations',
       'cancelled_escrow_information': 'Informations sur l\'Escrow Annulé',
       'could_not_launch_url': 'Impossible de lancer l\'URL',
       'attachment': 'Pièce jointe',
       'otp_resent_successfully': 'OTP renvoyé avec succès',
       'failed_to_resend_otp': 'Échec du renvoi de l\'OTP',
               // Transaction screen translations
        'all_transactions': 'Toutes les Transactions',
        'filters': 'Filtres',
        'all_types': 'Tous les Types',
        'withdrawals': 'Retraits',
        'deposits': 'Dépôts',
        'operators': 'Opérateurs',
        'select_method': 'Sélectionner la Méthode',
      'select_date': 'Sélectionner la Date',
        'all_status': 'Tous les Statuts',
        'time_order': 'Ordre Temporel',
        'time_ascending': 'Temps Croissant',
        'time_descending': 'Temps Décroissant',
        'from_date': 'Date de début',
        'to_date': 'Date de fin',
        'phone_number': 'Numéro de Téléphone',
                 'view': 'Voir',
         'no_data_available': 'Aucune Donnée Disponible',
                  'activity_title': 'Titre de l\'Activité',
         'balance': 'Solde',
         'merchant': 'Marchand',
         'add_sub_account': 'AJOUTER UN COMPTE SOUS',
         'no_sub_accounts_found': 'Aucun compte sous trouvé',
         'sub_account_name': 'Nom du Compte Sous:',
      'please_enter_sub_account_name': 'Veuillez entrer le nom du compte sous',
         'mtn_orange_balance': 'Solde MTN & Orange:',
         'detail': 'Détail',
         'transfer_in': 'Transfert Entrant',
         'transfer_out': 'Transfert Sortant',
                   'please_contact_support_to_update_the_sub_account': 'Veuillez contacter le support pour mettre à jour le compte sous',
          'transaction_history': 'Historique des Transactions',
          'filter': 'Filtre',
          'today': 'Aujourd\'hui',
          'weekly': 'Cette Semaine',
          'monthly': 'Ce Mois',
          'yearly': 'Cette Année',
          'no_transactions_found': 'Aucune Transaction Trouvée',
          'no_transactions_for_sub_account': 'Il n\'y a pas encore de transactions pour ce compte sous.',
          'transaction_id': 'ID de Transaction',
          'date_time': 'Date et Heure',
          'method': 'Méthode',
          'description': 'Description',
          'gross_amount': 'Montant Brut',
          'fee': 'Frais',
          'net_amount': 'Montant Net',
          'balance': 'Solde',
    },
  };
}
